AWSTemplateFormatVersion: 2010-09-09
Resources:
  desafioCoder14:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value:  desafioCoder14
